-- AlterTable: add retry_count to videos
ALTER TABLE "videos" ADD COLUMN "retry_count" INTEGER NOT NULL DEFAULT 0;

-- AlterTable: add search_vector tsvector column (not generated by Prisma)
ALTER TABLE "videos" ADD COLUMN "search_vector" tsvector;

-- CreateIndex: GIN index for full-text search
CREATE INDEX "ix_videos_search_vector" ON "videos" USING GIN("search_vector");

-- CreateTable: transcription_segments
CREATE TABLE "transcription_segments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "video_id" UUID NOT NULL,
    "start_ms" INTEGER NOT NULL,
    "end_ms" INTEGER NOT NULL,
    "text" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "transcription_segments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ix_ts_video_id" ON "transcription_segments"("video_id");

-- AddForeignKey
ALTER TABLE "transcription_segments" ADD CONSTRAINT "transcription_segments_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "videos"("id") ON DELETE CASCADE ON UPDATE CASCADE;
